# Install with `mamba env create -f environment.yml`
name: winter_school
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - numpy
  - matplotlib
  - xarray
  - scipy
  - proplot
  - cartopy
  - netcdf4
  - tqdm
  - xdem
  - jupytext